# Generated by Django 5.1.11 on 2025-08-01 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracionRenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('presentada', 'Presentada'), ('pagada', 'Pagada')], default='borrador', max_length=20)),
                ('residencia_2024', models.CharField(blank=True, max_length=32, null=True)),
                ('residencia_365', models.CharField(blank=True, max_length=32, null=True)),
                ('nacionalidad_colombiana', models.CharField(blank=True, max_length=8, null=True)),
                ('servicio_estado_exterior', models.CharField(blank=True, max_length=8, null=True)),
                ('es_residente', models.BooleanField(default=False)),
                ('formulario_tipo', models.CharField(blank=True, max_length=8, null=True)),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('dv', models.CharField(blank=True, max_length=2, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=64, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=64, null=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=64, null=True)),
                ('otros_nombres', models.CharField(blank=True, max_length=64, null=True)),
                ('genero', models.CharField(blank=True, max_length=32, null=True)),
                ('direccion_seccional', models.CharField(blank=True, max_length=8, null=True)),
                ('actividad_economica', models.CharField(blank=True, max_length=64, null=True)),
                ('patrimonio_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('deudas', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('ingresos_brutos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('renta_liquida', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('impuesto_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('saldo_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('saldo_a_favor', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagoDeclaracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('referencia_pago', models.CharField(max_length=32)),
                ('valor_pagado', models.DecimalField(decimal_places=2, max_digits=16)),
                ('estado', models.CharField(default='exitoso', max_length=16)),
                ('declaracion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='renta.declaracionrenta')),
            ],
        ),
    ]
