# Generated by Django 5.1.11 on 2025-08-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagodeclaracion',
            name='metodo_pago',
            field=models.CharField(choices=[('pse', 'PSE'), ('tarjeta', 'Tarjeta de Crédito')], default='pse', max_length=20),
        ),
    ]
